version: "3"

services:
    springboot:
        container_name: ordering-system-ws
        build: .
        depends_on:
            - database
        ports:
            - 9200:9200
        restart:
            on-failure

    database:
        image: "postgres:15.0"
        container_name: ordering-system-db
        environment:
            POSTGRES_USER: lorem
            POSTGRES_PASSWORD: ipsum22
            POSTGRES_DB: ordering-system
        expose:
            - 5432
        volumes:
            - ./db-data/:/var/lib/postgresql/data/
            - ./src/main/resources/dbschema/orderingsystem.sql:/scripts/orderingsystem.sql
        restart:
            unless-stopped